Studon7 update722
ilifau/StudOn pull request #28
Opened 2023-06-12 08:28 UTC by chrfau

2023-06-13 07:22 UTC, fneumann reviewed
Siehe Kommentare

2023-06-13 07:22 UTC, fneumann commented on Services/WebServices/SOAP/classes/class.ilSoapClient.php
> +    private $client = null;
Bin nicht sicher, ob das implizit für andere Anpassungen angenomemn ird. Am besten die abgeleiteten Klassen checken.

2023-06-13 07:22 UTC, fneumann commented on Modules/Course/classes/class.ilCourseConstants.php
> +// fau: campusSub - add constant for mycampus subscription (do not remove with mycampus yet as still used by other functionality e.g. univis import)
wir müssten mit einer DB-Abfrage bei den Kursen die Anmelung über mein campus aud deaktiviert ändern.

2023-06-13 07:22 UTC, fneumann commented on Customizing/global/lang/ilias_de.lang.local
> -univis#:#crs_availability_unvisible_info#:#Der Kurs wird offline geschaltet
Einige dieser Sprachvariablen könnten auch für andere Anpassungen verwendet worden sein.

2023-06-13 07:22 UTC, fneumann commented on Customizing/apply_patches.php
> -//$p->applyPatch('ilUnivisPatches.dropUnivisTables');
Die univis-Tabellen müssen wir nachträglich löschen. Wenn sie nur in StudOn existieren, reicht es, sie in der StudOn-Datenbank direkt von Hand zu löschen. Falls mehr Plattformen betroffen sind, am besten per Custom-Update-Step mit Prüfung, ob die Tabellen existieren.

2023-06-13 07:22 UTC, fneumann commented on Modules/Course/classes/class.ilObjCourseGUI.php
> -            // fau: univisInfo - don't modify string if html is contained
**Bitte als neue Anpasung courseInfoRte drin lassen!** Der Univis-Import war der Anlass, dass wir Important Information und Syllabus als Richtext-Felder umgesetzt haben, weil hier HTML-Daten aus Univis eingespielt wurden. Aber die Möglichkeit zum Richtext ist jetzt bei beliebigen Kursen (auch den Campo-Kursen) so und wird auch verwendet. Das könenn wir nicht einfach spontan zurückbuen - allenfalls mit Ankündigung beim Update auf ILIAS 8.

2023-06-13 07:22 UTC, fneumann commented on Modules/Course/classes/class.ilObjCourseGUI.php
> -            // fau: univisInfo - don't modify string if html is contained
s.o. courseInfoRte

2023-06-13 07:22 UTC, fneumann commented on Modules/Course/classes/class.ilObjCourseGUI.php
> -
s.o. courseInfoRte

2023-06-13 07:22 UTC, fneumann commented on Modules/Course/classes/class.ilObjCourseGUI.php
> -        // fau: univisInfo - use RTE / HTML for syllabus
s.o. courseInfoRte

2023-06-13 07:22 UTC, fneumann commented on Modules/Course/classes/class.ilObjCourseGUI.php
> -        // fau: univisInfo - allow HTML in course info
s.o. courseInfoRte

2023-06-13 07:22 UTC, fneumann commented on Services/Object/classes/class.ilObject.php
> -    public static function _getImportIdForObjectId($a_obj_id)
prüfen, ob anderweitig verwendet

2023-06-13 07:22 UTC, fneumann commented on Services/Utilities/classes/class.ilUtil.php
> -        // fau: univisInfo - mask existing href tags
Könnte bei vorhandenen Kursinfos noch relevant sein. Siehe courseInfoRte. Das Problem ist, dass makeClickable keinen beeits vorhandenen Html-Code erwartet - der kann aber durch den RTE kommen. die Anpassung ist ein Versuch, dass das keine Probleme bereitet. Prüfen, was passiert, wenn man in die Kursinfo per Tiny einen Link einfügt und dann die Info anzeigt.

2023-06-13 07:22 UTC, fneumann commented on templates/default/tpl.adm_content.html
> -<!-- BEGIN sr_focus -->
Hängen die Änderungen in dieser Datei mit der Unvis-Anpassung zusammen oder kamen sie durch das Update?

2023-06-15 07:53 UTC, chrfau commented on Services/WebServices/SOAP/classes/class.ilSoapClient.php
> +    private $client = null;
$client wird in den abgeleiteten Klassen nicht verwendet

2023-06-15 07:59 UTC, chrfau commented on Services/Object/classes/class.ilObject.php
> -    public static function _getImportIdForObjectId($a_obj_id)
Wird nicht mehr anderweitig verwendet, Wurde lediglich im Univis Service verwendet.

2023-06-15 08:37 UTC, chrfau commented on templates/default/tpl.adm_content.html
> -<!-- BEGIN sr_focus -->
Es sollte nur die Univis-Anpassung sein. Tatsächlich hatte ich hier anscheinend etwas falsch gemacht und im nächsten Commit wieder korrigiert https://github.com/ilifau/StudOn/pull/28/commits/2cc305897e492136568b2c0acb2d5ce0d6d32a7d#diff-c0bdaa19db329aff440ccb311ec7c5b35f22e869fcfe0c2e26ac145b196b629b

2023-06-15 11:28 UTC, chrfau commented on Customizing/apply_patches.php
> -//$p->applyPatch('ilUnivisPatches.dropUnivisTables');
Besprechung in Daily

2023-06-15 11:56 UTC, chrfau commented on Modules/Course/classes/class.ilCourseConstants.php
> +// fau: campusSub - add constant for mycampus subscription (do not remove with mycampus yet as still used by other functionality e.g. univis import)
Besprechung in Daily

2023-06-16 10:40 UTC, chrfau commented on Customizing/global/lang/ilias_de.lang.local
> -univis#:#crs_availability_unvisible_info#:#Der Kurs wird offline geschaltet
Den Aufruf $this->lng->loadLanguageModule("univis"); habe ich nur im Univis Service gefunden (Klasse ilUnivisImportLecturesGUI)

2023-06-19 17:26 UTC, chrfau commented on Modules/Course/classes/class.ilObjCourseGUI.php
> -            // fau: univisInfo - don't modify string if html is contained
done

2023-06-19 17:26 UTC, chrfau commented on Modules/Course/classes/class.ilObjCourseGUI.php
> -        // fau: univisInfo - use RTE / HTML for syllabus
done

2023-06-19 17:27 UTC, chrfau commented on Services/Utilities/classes/class.ilUtil.php
> -        // fau: univisInfo - mask existing href tags
done

2023-06-20 10:32 UTC, fneumann requested changes
Please have a look at the comment for "remove fau: fixOrderingExportXls".
The rest looks ok to me.

2023-06-20 10:32 UTC, fneumann commented on Modules/TestQuestionPool/classes/class.assOrderingQuestion.php
> -            // fau: fixOrderingExportXls - avoid error on empty elements
Die Änderung bei ILIAS verschiebt nur den Index von 1 auf 2:
https://github.com/ILIAS-eLearning/ILIAS/commit/968484249cf691d3145256e15923fe302efa214e#diff-d942456d4f47ddd5d489a0e432ac873b28e27302b1217c33ac32bb921bb3c198

Der StudOn-fix bezog sich aber auf das umschließende if, um Fehler bei einem leeren Element zu vermeiden.

2023-06-20 12:29 UTC, chrfau commented on Modules/TestQuestionPool/classes/class.assOrderingQuestion.php
> -            // fau: fixOrderingExportXls - avoid error on empty elements
reverted

2023-06-28 06:45 UTC, merged